# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autosubmit.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(582, 406)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/תמונות/CollegeLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.hello_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.hello_label.setFont(font)
        self.hello_label.setObjectName("hello_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.hello_label)
        self.username_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username_input = QtWidgets.QLineEdit(Form)
        self.username_input.setObjectName("username_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.username_input)
        self.password_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_input = QtWidgets.QLineEdit(Form)
        self.password_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password_input)
        self.save_login_checkBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.save_login_checkBox.setFont(font)
        self.save_login_checkBox.setObjectName("save_login_checkBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.save_login_checkBox)
        self.courses_comboBox_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.courses_comboBox_label.setFont(font)
        self.courses_comboBox_label.setObjectName("courses_comboBox_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.courses_comboBox_label)
        self.courses_comboBox = QtWidgets.QComboBox(Form)
        self.courses_comboBox.setObjectName("courses_comboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.courses_comboBox)
        self.assignment_number_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.assignment_number_label.setFont(font)
        self.assignment_number_label.setObjectName("assignment_number_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.assignment_number_label)
        self.assignment_number_input = QtWidgets.QLineEdit(Form)
        self.assignment_number_input.setText("")
        self.assignment_number_input.setObjectName("assignment_number_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.assignment_number_input)
        self.file_name_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.file_name_label.setFont(font)
        self.file_name_label.setObjectName("file_name_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.file_name_label)
        self.file_path_text = QtWidgets.QLineEdit(Form)
        self.file_path_text.setObjectName("file_path_text")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.file_path_text)
        self.browse_file_button = QtWidgets.QPushButton(Form)
        self.browse_file_button.setObjectName("browse_file_button")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.browse_file_button)
        self.submit_button = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.submit_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SubmitTool"))
        self.hello_label.setText(_translate("Form", "Hey,\n"
"This is auto submit tool for Azrieli college\n"
"Enjoy!\n"
""))
        self.username_label.setText(_translate("Form", "Username"))
        self.password_label.setText(_translate("Form", "Password"))
        self.save_login_checkBox.setText(_translate("Form", "Save login for later?"))
        self.courses_comboBox_label.setText(_translate("Form", "Choose course"))
        self.assignment_number_label.setText(_translate("Form", "Assignment Number"))
        self.file_name_label.setText(_translate("Form", "File Name"))
        self.browse_file_button.setText(_translate("Form", "Browse File"))
        self.submit_button.setText(_translate("Form", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

